run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocyclo
    - gofmt
    - goimports
    - revive
    - unparam
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet