CREATE TABLE reservations (
      id UUID PRIMARY KEY,
      user_id UUID REFERENCES users(id) ON DELETE CASCADE,
      room_number INT NOT NULL,
      check_in BOOLEAN NOT NULL DEFAULT FALSE,
      check_out BOOLEAN NOT NULL DEFAULT FALSE,
      hour_entry TIMESTAMP WITH TIME ZONE NOT NULL,
      hour_out TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);